### PR TITLE
Version bump.

### PR DESCRIPTION
**Pull request by IngoValente**
Adds support for video.js v5 in the npm version.

Should also maybe consider removing video.js from devDependencies & dependencies in package.json, as peerDependency only should be sufficient?

### CODE REVIEW

**Comment by matthojo** [comment]
Thank you for your PR. This only appears to update the package.json version for this repo though :)

**Comment by IngoValente** [comment]
Ah yes forgot about bower. Also added it to the build files, like you did in the previous bump.
Should be ok now, or am I missing something?

**Comment by matthojo** [comment]
All good! Thanks.

**Comment by IngoValente** [comment]
Oops, seems like it broke the npm package. Somehow when I install it now, the dist folder is not included, and thus it doesn't find the main file. Any idea why?

**Comment by matthojo** [comment]
How are you installing it, via `npm`?

**Comment by IngoValente** [comment]
Yes just running `npm install videojs-background`.
Weird thing is that the bower files are correctly ignored and not downloaded.

A solution would be to change the npm main file to point to the lib folder, and let the dist folder be for the bower users.

**Comment by matthojo** [comment]
What version of `npm` are you using?

**Comment by IngoValente** [comment]
Ah yes that could be it. I'm using 3.3.12, the package says 2.14.11.
Before this commit it worked fine though?

**Pull request merged**
